[workspace]
members = [
    "paytube-svm",
    "solana-svm",
]
resolver = "2"

[workspace.dependencies]
solana-bpf-loader-program = { git = "https://github.com/anza-xyz/agave.git", ref = "cd7710ba1abe5a7d5c29ddf16e07e872c354808b" }
solana-client = { git = "https://github.com/anza-xyz/agave.git", ref = "cd7710ba1abe5a7d5c29ddf16e07e872c354808b" }
solana-logger = { git = "https://github.com/anza-xyz/agave.git", ref = "cd7710ba1abe5a7d5c29ddf16e07e872c354808b" }
solana-measure = { git = "https://github.com/anza-xyz/agave.git", ref = "cd7710ba1abe5a7d5c29ddf16e07e872c354808b" }
solana-metrics = { git = "https://github.com/anza-xyz/agave.git", ref = "cd7710ba1abe5a7d5c29ddf16e07e872c354808b" }
solana-program-runtime = { git = "https://github.com/anza-xyz/agave.git", ref = "cd7710ba1abe5a7d5c29ddf16e07e872c354808b" }
solana-sdk = { git = "https://github.com/anza-xyz/agave.git", ref = "cd7710ba1abe5a7d5c29ddf16e07e872c354808b" }
solana-system-program = { git = "https://github.com/anza-xyz/agave.git", ref = "cd7710ba1abe5a7d5c29ddf16e07e872c354808b" }
solana-test-validator = { git = "https://github.com/anza-xyz/agave.git", ref = "cd7710ba1abe5a7d5c29ddf16e07e872c354808b" }

[patch.crates-io]
solana-program = { git = "https://github.com/anza-xyz/agave.git", ref = "cd7710ba1abe5a7d5c29ddf16e07e872c354808b" }
solana-zk-sdk = { git = "https://github.com/anza-xyz/agave.git", ref = "cd7710ba1abe5a7d5c29ddf16e07e872c354808b" }
solana-zk-token-sdk = { git = "https://github.com/anza-xyz/agave.git", ref = "cd7710ba1abe5a7d5c29ddf16e07e872c354808b" }
