[package]
name = "paytube-svm"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
solana-bpf-loader-program = { workspace = true }
solana-program-runtime = { workspace = true }
solana-sdk = { workspace = true }
solana-svm = { path = "../solana-svm" }
